import os

POSTGRES_USER = os.getenv("POSTGRES_USER", "admin1")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "admin1")
POSTGRES_DB = os.getenv("POSTGRES_DB", "fastapi_db")
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "localhost")
POSTGRES_PORT = os.getenv("POSTGRES_PORT", "5432")

DATABASE_URL = f"postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
